/**
 * Flowko U13-07: embed.js runs on clients' websites. Nothing compiled into it may load a resource
 * from a third-party host (a remote font would send every visitor's IP address to that host), and
 * it must not reference any cal.com origin.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const srcDir: string = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

// A scheme-relative or absolute URL on cal.com or any of its subdomains (app.cal.com, ...).
const CAL_COM_ORIGIN = /(?:https?:)?\/\/(?:[a-z0-9-]+\.)*cal\.com(?![a-z0-9-])/i;
// A string literal that starts with a bare cal.com host: "cal.com", 'app.cal.com', `.cal.com`.
// Such a literal survives minification (e.g. a hostname comparison). Prose in comments does not match.
const CAL_COM_HOST_LITERAL = /["'`]\.?(?:[a-z0-9-]+\.)*cal\.com(?![a-z0-9-])/i;
// url(...) whose target is not local: http(s)://, scheme-relative //, or any other scheme but data:.
const REMOTE_CSS_URL = /url\(\s*['"]?\s*(?:\/\/|(?!data:)[a-z][a-z0-9+.-]*:)/i;
// @import "https://..." / @import url(https://...) / @import "//..."
const REMOTE_CSS_IMPORT = /@import\s+(?:url\(\s*)?['"]?\s*(?:\/\/|[a-z][a-z0-9+.-]*:)/i;

function read(file: string): string {
  return fs.readFileSync(file, "utf8");
}

/** Source files that can end up in embed.js (tests and the gitignored Tailwind output excluded). */
function listSourceFiles(dir: string): string[] {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      return entry.name === "__tests__" ? [] : listSourceFiles(full);
    }
    if (!/\.(ts|tsx|css)$/.test(entry.name)) return [];
    if (/\.(test|spec)\.(ts|tsx)$/.test(entry.name)) return [];
    if (entry.name === "tailwind.generated.css") return [];
    return [full];
  });
}

/**
 * Resolves a CSS @import specifier the way the Tailwind build does: relative paths against the
 * importing file, bare package specifiers through node_modules and the package's "exports" map with
 * the "style" condition (tw-animate-css and tailwindcss export their CSS only under "style").
 */
function resolveCssImport(spec: string, fromFile: string): string {
  if (spec.startsWith(".") || spec.startsWith("/")) return path.resolve(path.dirname(fromFile), spec);

  const segments = spec.split("/");
  const pkgName = spec.startsWith("@") ? segments.slice(0, 2).join("/") : segments[0];
  const subpath = `.${spec.slice(pkgName.length)}`;

  for (let dir = path.dirname(fromFile); ; dir = path.dirname(dir)) {
    const pkgDir = path.join(dir, "node_modules", pkgName);
    const pkgJsonPath = path.join(pkgDir, "package.json");
    if (fs.existsSync(pkgJsonPath)) {
      const pkg = JSON.parse(read(pkgJsonPath));
      const entry = pkg.exports?.[subpath];
      const target = typeof entry === "string" ? entry : (entry?.style ?? entry?.default);
      if (target) return path.resolve(pkgDir, target);
      if (subpath === ".") return path.resolve(pkgDir, pkg.style ?? pkg.main);
      return path.resolve(pkgDir, subpath);
    }
    if (path.dirname(dir) === dir) throw new Error(`Cannot resolve CSS import "${spec}" from ${fromFile}`);
  }
}

/**
 * Every CSS file styles.css pulls in, following @import recursively (styles.css itself excluded).
 * Remote specifiers are not followed; the REMOTE_CSS_IMPORT assertion flags them in the importing file.
 * Output generated by @plugin lines is not visible here; the grep on the built embed.js covers it.
 */
function resolveStylesImports(): string[] {
  const seen = new Set<string>();
  const visit = (file: string): void => {
    const css = read(file).replace(/\/\*[\s\S]*?\*\//g, "");
    for (const [, spec] of css.matchAll(/@import\s+(?:url\(\s*)?['"]([^'"]+)['"]/g)) {
      if (/^(?:\/\/|[a-z][a-z0-9+.-]*:)/i.test(spec)) continue;
      const resolved = resolveCssImport(spec, file);
      if (seen.has(resolved)) continue;
      seen.add(resolved);
      visit(resolved);
    }
  };
  visit(path.join(srcDir, "styles.css"));
  return [...seen];
}

describe("embed-core has no third-party resources (U13-07)", () => {
  it("styles.css declares no @font-face, no remote url() and no Cal Sans heading font", () => {
    const css = read(path.join(srcDir, "styles.css"));

    expect(css).not.toMatch(/@font-face/i);
    expect(css).not.toMatch(REMOTE_CSS_URL);
    expect(css).not.toMatch(REMOTE_CSS_IMPORT);
    expect(css).not.toMatch(/cal\.ttf/i);
    expect(css).not.toMatch(/Cal Sans/i);
    expect(css).not.toMatch(/cal\.com/i);
  });

  it("no CSS bundled into embed.js (styles.css and its @imports, recursively) loads a remote url() or declares @font-face", () => {
    const imported = resolveStylesImports();
    // Guard against a vacuous pass: the direct imports (tailwindcss, the coss-ui package, the shared
    // tokens) and the second-level import tokens.css pulls in (tw-animate-css) must all be followed.
    for (const expected of [
      path.join("tailwindcss", "index.css"),
      path.join("styles", "globals.css"),
      path.join("config", "theme", "tokens.css"),
      path.join("tw-animate-css", "dist", "tw-animate.css"),
    ]) {
      expect({ expected, followed: imported.some((file) => file.endsWith(expected)) }).toEqual({
        expected,
        followed: true,
      });
    }

    const cssFiles = [
      path.join(srcDir, "styles.css"),
      path.join(srcDir, "embed.css"),
      path.join(srcDir, "loader.css"),
      ...imported,
    ];

    for (const file of cssFiles) {
      const css = read(file);
      expect({ file, remoteUrl: REMOTE_CSS_URL.test(css) }).toEqual({ file, remoteUrl: false });
      expect({ file, remoteImport: REMOTE_CSS_IMPORT.test(css) }).toEqual({ file, remoteImport: false });
      expect({ file, fontFace: /@font-face/i.test(css) }).toEqual({ file, fontFace: false });
    }
  });

  it("no embed-core source file references a cal.com origin, a quoted cal.com host or cal.ttf", () => {
    const files = listSourceFiles(srcDir);
    // Guard against a vacuous pass: the files that build embed.js must be in the scan.
    for (const required of ["embed.ts", "styles.css", "embed.css", "loader.css", "preview.ts"]) {
      expect(files).toContain(path.join(srcDir, required));
    }

    const offenders = files
      .filter((file) => {
        const content = read(file);
        return (
          CAL_COM_ORIGIN.test(content) || CAL_COM_HOST_LITERAL.test(content) || /cal\.ttf/i.test(content)
        );
      })
      .map((file) => path.relative(srcDir, file));

    expect(offenders).toEqual([]);
  });

  it("the cal.com origin pattern catches the shapes it must catch", () => {
    for (const hit of [
      "https://cal.com/cal.ttf",
      '"https://cal.com"',
      "https://app.cal.com",
      "//cal.com/x",
      "http://CAL.COM",
    ]) {
      expect({ hit, matched: CAL_COM_ORIGIN.test(hit) }).toEqual({ hit, matched: true });
    }
    for (const miss of ["https://booking.flowko.si", "https://cal.community", "cal.com has rewrite issues"]) {
      expect({ miss, matched: CAL_COM_ORIGIN.test(miss) }).toEqual({ miss, matched: false });
    }
    for (const hit of ['hostname === "app.cal.com"', "host.endsWith('.cal.com')", "`cal.com`", '"CAL.COM"']) {
      expect({ hit, matched: CAL_COM_HOST_LITERAL.test(hit) }).toEqual({ hit, matched: true });
    }
    for (const miss of [
      "// Generally it would be cal.com but in case of self hosting it can be anything.",
      '"Looks like you have iframed cal.com but not using Embed Snippet."',
      '"cal.community"',
      '"booking.flowko.si"',
    ]) {
      expect({ miss, matched: CAL_COM_HOST_LITERAL.test(miss) }).toEqual({ miss, matched: false });
    }
    expect(REMOTE_CSS_URL.test('src: url("https://example.com/font.ttf")')).toBe(true);
    expect(REMOTE_CSS_URL.test("url(//example.com/font.ttf)")).toBe(true);
    expect(REMOTE_CSS_URL.test("url(data:image/svg+xml;base64,AAAA)")).toBe(false);
    expect(REMOTE_CSS_URL.test('url("./local.svg")')).toBe(false);
    expect(REMOTE_CSS_IMPORT.test('@import url("https://fonts.example.com/css")')).toBe(true);
    expect(REMOTE_CSS_IMPORT.test('@import "../../../config/theme/tokens.css";')).toBe(false);
  });
});
